openapi: 3.0.0
info:
  title: APM UI
  version: 1.0.0
  description: Kibana APIs for working with the APM UI.
  license:
    name: Elastic License 2.0
    url: https://www.elastic.co/licensing/elastic-license
tags:
  - name: APM agent configuration
    description: |
      Fine tune your APM agent configuration without redeploying your application.
    externalDocs:
      description: APM agent central config docs
      url: https://www.elastic.co/guide/en/observability/current/apm-agent-configuration.html#_supported_configurations
  - name: APM agent keys
    description: |
      Configure APM agent keys to authorize requests from APM agents to the APM Server.
    externalDocs:
      description: APM agent API key docs
      url: https://www.elastic.co/guide/en/observability/current/apm-api-key.html
  - name: APM annotations
    description: |
      Annotate visualizations in the APM UI with significant events. Annotations enable you to easily see how events are impacting the performance of your applications.
    externalDocs:
      description: APM annotations docs
      url: https://www.elastic.co/guide/en/observability/current/apm-transactions-annotations.html
  - name: APM source maps
    description: |
      Upload source maps to map minified files back to original source code. Source maps allow you to maintain the speed advantage of minified code without losing the ability to debug your application.
    externalDocs:
      description: APM source map docs
      url: https://www.elastic.co/guide/en/observability/current/apm-source-map-how-to.html
paths:
  /api/apm/agent_keys:
    post:
      summary: Create an APM agent key
      description: |
        Create an APM agent API key.
        Specify API key privileges in the request body at creation time.

        You must have at least the `manage_own_api_key` cluster privilege and the APM application-level privileges that it wishes to grant.
      operationId: createAgentKey
      tags:
        - APM agent keys
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: The name of the APM agent key.
                  type: string
                  example: my-new-apm-key
                privileges:
                  description: |
                    APM agent key privileges. It can take one or more of the following values:

                    * `event:write`: Required for ingesting APM agent events.
                    * `config_agent:read`: Required for APM agents to read agent configuration remotely.
                  type: array
                  items:
                    type: string
                    enum:
                      - event:write
                      - config_agent:read
                  example:
                    - event:write
                    - config_agent:read
              required:
                - name
                - privileges
      responses:
        '200':
          description: The agent key was created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                    example: PjGloCGOTzaZr8ilUPvkjA
                  expiration:
                    type: integer
                    format: int64
                  id:
                    type: string
                    example: 3DCLmn0B3ZMhLUa7WBG9
                  name:
                    type: string
                    example: my-new-apm-key
                  encoded:
                    type: string
                    example: M0RDTG1uMEIzWk1oTFVhN1dCRzk6UGpHbG9DR09UemFacjhpbFVQdmtqQQ
  /api/apm/services/{serviceName}/annotation:
    post:
      summary: Create or update an annotation
      description: |
        Create a new annotation for a specific service.
        By default, annotations are stored in a newly created `observability-annotations` index.
        The name of this index can be changed in your `config.yml` by editing `xpack.observability.annotations.index`.
        If you change the default index name, youâ€™ll also need to update your [user privileges](https://www.elastic.co/guide/en/observability/current/apm-app-annotation-user-create.html) accordingly.
      operationId: createAnnotation
      tags:
        - APM annotations
      parameters:
        - name: serviceName
          in: path
          required: true
          description: The name of the service.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: object
                  description: Service identifying the configuration to create or update.
                  properties:
                    version:
                      type: string
                      description: Version of service.
                      example: '1.2'
                    environment:
                      type: string
                      description: Environment of service.
                      example: production
                  required:
                    - version
                '@timestamp':
                  type: string
                  description: |
                    The date and time of the annotation.
                    Must be in [ISO 8601](https://www.w3.org/TR/NOTE-datetime) format.
                  example: '2024-07-21T10:31:30.452Z'
                message:
                  type: string
                  description: The message displayed in the annotation.
                  example: Deployment 1.2
                  default: service.version
                tags:
                  type: array
                  description: |
                    Distinguish APM annotations from other annotations.
                    Defaults to `["apm"]`, and while you can add additional tags, you cannot remove the `apm` tag.
                  items:
                    type: string
                  default:
                    - apm
                  example:
                    - apm
                    - my-tag
              required:
                - '@timestamp'
                - service
      responses:
        '200':
          description: Annotation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _index:
                    type: string
                    example: observability-annotations
                  _id:
                    type: string
                    example: Lc9I93EBh6DbmkeV7nFX
                  _version:
                    type: integer
                    example: 1
                  _seq_no:
                    type: integer
                    example: 0
                  _primary_term:
                    type: integer
                    example: 1
                  found:
                    type: boolean
                    example: true
                  _source:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Deployment 1.2
                      '@timestamp':
                        type: string
                        example: '2024-07-21T10:31:30.452Z'
                      service:
                        type: object
                        properties:
                          version:
                            type: string
                            example: '1.2'
                          name:
                            type: string
                            example: my-node-service
                          environment:
                            type: string
                      annotation:
                        type: object
                        properties:
                          type:
                            type: string
                            example: deployment
                      tags:
                        type: array
                        items:
                          type: string
                        example:
                          - apm
                          - elastic.co
                          - customer
                      event:
                        type: object
                        properties:
                          created:
                            type: string
                            example: '2024-08-30T15:46:43.259Z'
  /api/apm/services/{serviceName}/annotation/search:
    get:
      summary: Search for annotations
      description: Search for annotations related to a specific service.
      operationId: getAnnotation
      tags:
        - APM annotations
      parameters:
        - name: serviceName
          in: path
          required: true
          description: The name of the service.
          schema:
            type: string
        - name: environment
          in: query
          required: false
          description: The environment to filter annotations by.
          schema:
            type: string
        - name: start
          in: query
          required: false
          description: The start date for the search.
          schema:
            type: string
        - name: end
          in: query
          required: false
          description: The end date for the search.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  annotations:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - version
                        id:
                          type: string
                        '@timestamp':
                          type: number
                          example: 1721557890452
                        text:
                          type: string
                          example: Deployment 1.2
  /api/apm/sourcemaps:
    post:
      summary: Create or update a source map
      operationId: createSourcemap
      tags:
        - APM source maps
      description: |
        Create or update a source map for a specific service and version.

        You must have `All` Kibana privileges for the APM and User Experience feature. For more information, refer to [Kibana privileges](https://www.elastic.co/guide/en/kibana/current/kibana-privileges.html).
      requestBody:
        content:
          application/json; Elastic-Api-Version=2023-10-31:
            schema:
              type: object
              properties:
                service_name:
                  description: The name of the service that the source map should apply to.
                  type: string
                service_version:
                  description: The version of the service that the source map should apply to.
                  type: string
                bundle_filepath:
                  description: The absolute path of the final bundle as used in the web application.
                  type: string
                sourcemap:
                  description: The source map. It must follow the [source map revision 3 proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k).
                  type: string
              required:
                - service_name
                - service_version
                - bundle_filepath
                - sourcemap
            examples:
              file:
                summary: Upload a source map as a file.
                value:
                  service_name: foo
                  service_version: 1.0.0
                  bundle_filepath: /test/e2e/general-usecase/bundle.js
                  sourcemap: '@path/to/source_map/bundle.js.map'
              inline:
                summary: Include the source map contents inline.
                value:
                  value: null
                  service_name: foo
                  service_version: 1.0.0
                  bundle_filepath: /test/e2e/general-usecase/bundle.js
                  sourcemap: '{\"version\":3,\"file\":\"static/js/main.chunk.js\",\"sources\":[\"fleet-source-map-client/src/index.css\",\"fleet-source-map-client/src/App.js\",\"webpack:///./src/index.css?bb0a\",\"fleet-source-map-client/src/index.js\",\"fleet-source-map-client/src/reportWebVitals.js\"],\"sourcesContent\":[\"content\"],\"mappings\":\"mapping\",\"sourceRoot\":\"\"}'
      responses:
        '200':
          description: Source map successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: sourcemap
                  identifier:
                    type: string
                    example: foo-1.0.0
                  relative_url:
                    type: string
                    example: /api/fleet/artifacts/foo-1.0.0/644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                  body:
                    type: string
                    example: eJyFkL1OwzAUhd/Fc+MbYMuCEBIbHRjKgBgc96R16tiWr1OQqr47NwqJxEK3q/PzWccXxchnZ7E1A1SjuhjVZtF2yOxiEPlO17oWox3D3uPFeSRTjmJQARfCPeiAgGx8NTKsYdAc1T3rwaSJGcds8Sp3c1HnhfywUZ3QhMTFFGepZxqMC9oex3CS9tpk1XyozgOlmoVKuJX1DqEQZ0su7PGtLU+V/3JPKc3cL7TJ2FNDRPov4bFta3MDM4f7W69lpJjLO9qdK8bzVPhcJz3HUCQ4LbO/p5hCSC4cZPByrp/wFqOklbpefwAhzpqI
                  created:
                    format: date-time
                    type: string
                    example: '2021-07-09T20:47:44.812Z'
                  id:
                    type: string
                    example: apm:foo-1.0.0-644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                  compressionAlgorithm:
                    type: string
                    example: zlib
                  decodedSha256:
                    type: string
                    example: 644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                  decodedSize:
                    type: number
                    example: 441
                  encodedSha256:
                    type: string
                    example: 024c72749c3e3dd411b103f7040ae62633558608f480bce4b108cf5b2275bd24
                  encodedSize:
                    type: number
                    example: 237
                  encryptionAlgorithm:
                    type: string
                    example: none
                  packageName:
                    type: string
                    example: apm
    get:
      summary: Get source maps
      operationId: getSourcemap
      tags:
        - APM source maps
      description: |
        Returns an array of Fleet artifacts, including source map uploads.

        You must have `Read` or `All` Kibana privileges for the APM and User Experience feature.
        For more information, refer to [Kibana privileges](https://www.elastic.co/guide/en/kibana/current/kibana-privileges.html).
      responses:
        '200':
          description: Source map successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  artifacts:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: sourcemap
                        identifier:
                          type: string
                          example: foo-1.0.0
                        relative_url:
                          type: string
                          example: /api/fleet/artifacts/foo-1.0.0/644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                        body:
                          type: object
                          properties:
                            serviceName:
                              type: string
                              example: foo
                            serviceVersion:
                              type: string
                              example: 1.0.0
                            bundleFilepath:
                              type: string
                              example: /test/e2e/general-usecase/bundle.js
                            sourceMap:
                              type: object
                              properties:
                                version:
                                  type: integer
                                  example: 3
                                file:
                                  type: string
                                  example: static/js/main.chunk.js
                                sources:
                                  type: array
                                  items:
                                    type: string
                                  example:
                                    - fleet-source-map-client/src/index.css
                                    - fleet-source-map-client/src/App.js
                                    - webpack:#/./src/index.css?bb0a
                                    - fleet-source-map-client/src/index.js
                                    - fleet-source-map-client/src/reportWebVitals.js
                                sourcesContent:
                                  type: array
                                  items:
                                    type: string
                                  example:
                                    - content
                                mappings:
                                  type: string
                                  example: mapping
                                sourceRoot:
                                  type: string
                        created:
                          type: string
                          example: '2021-07-09T20:47:44.812Z'
                        id:
                          type: string
                          example: apm:foo-1.0.0-644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                        compressionAlgorithm:
                          type: string
                          example: zlib
                        decodedSha256:
                          type: string
                          example: 644fd5a997d1ddd90ee131ba18e2b3d03931d89dd1fe4599143c0b3264b3e456
                        decodedSize:
                          type: number
                          example: 441
                        encodedSha256:
                          type: string
                          example: 024c72749c3e3dd411b103f7040ae62633558608f480bce4b108cf5b2275bd24
                        encodedSize:
                          type: number
                          example: 237
                        encryptionAlgorithm:
                          type: string
                          example: none
                        packageName:
                          type: string
                          example: apm
  /api/apm/sourcemaps/{id}:
    delete:
      summary: Delete a source map
      operationId: deleteSourcemap
      tags:
        - APM source maps
      description: |
        Delete a previously uploaded source map.

        You must have `All` Kibana privileges for the APM and User Experience feature.
        For more information, refer to [Kibana privileges](https://www.elastic.co/guide/en/kibana/current/kibana-privileges.html).
      parameters:
        - name: id
          in: path
          required: true
          description: The id of a previously uploaded source map.
          schema:
            type: string
      responses:
        '200':
          description: Source map successfully deleted.
          content:
            application/json:
              schema:
                type: object
  /api/apm/settings/agent-configuration:
    put:
      summary: Create or update a configuration
      description: Create or update an APM agent configuration.
      operationId: createApmAgentConfig
      tags:
        - APM agent configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: object
                  description: The service identifying the configuration to create or update.
                  properties:
                    name:
                      type: string
                      description: The name of the service.
                      example: frontend
                    environment:
                      type: string
                      description: The environment of the service.
                      example: production
                  required:
                    - name
                settings:
                  type: object
                  description: |
                    A key/value object with option name and option value. Each APM agent has a list of supported configurations. For more information, refer to the [APM agent documentation](https://www.elastic.co/guide/en/observability/current/apm-agent-configuration.html#_supported_configurations).
                  example:
                    transaction_sample_rate: '0.4'
                    capture_body: 'off'
                    transaction_max_spans: '500'
                agent_name:
                  type: string
                  description: The agent name. This is used by the UI to determine which settings to display.
                  example: nodejs
              required:
                - service
                - settings
      responses:
        '200':
          description: Configuration successfully created.
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: Delete a configuration
      description: |
        Delete an APM agent configuration.
      operationId: deleteApmAgentConfig
      tags:
        - APM agent configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: object
                  description: Service identifying the configuration to delete.
                  properties:
                    name:
                      type: string
                      description: Name of service.
                      example: frontend
                    environment:
                      type: string
                      description: Environment of service.
                      example: production
                  required:
                    - name
              required:
                - service
      responses:
        '200':
          description: Configuration successfully deleted.
          content:
            application/json:
              schema:
                type: object
    get:
      summary: Get configurations
      description: |
        List all APM agent configurations.
      operationId: listApmAgentConfig
      tags:
        - APM agent configuration
      responses:
        '200':
          description: Configuration successfully created.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    agent_name:
                      type: string
                    service:
                      type: object
                      properties:
                        name:
                          type: string
                        environment:
                          type: string
                    settings:
                      type: object
                    '@timestamp':
                      type: number
                    applied_by_agent:
                      type: boolean
                    etag:
                      type: string
              examples:
                basic:
                  summary: Response returning two configurations.
                  value:
                    items:
                      - agent_name: go
                        service:
                          name: opbeans-go
                          environment: production
                        settings:
                          transaction_sample_rate: '1'
                          capture_body: 'off'
                          transaction_max_spans: '200'
                        '@timestamp': 1581934104843
                        applied_by_agent: false
                        etag: 1e58c178efeebae15c25c539da740d21dee422fc
                      - agent_name: nodejs
                        service:
                          name: frontend
                        settings:
                          transaction_sample_rate: '1'
                        '@timestamp': 1582031336265
                        applied_by_agent: false
                        etag: 5080ed25785b7b19f32713681e79f46996801a5b
  /api/apm/settings/agent-configuration/search:
    post:
      summary: Search for a configuration
      description: Search for an APM agent configuration.
      operationId: searchApmAgentConfig
      tags:
        - APM agent configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: object
                  description: The service identifying the configuration to search.
                  properties:
                    name:
                      type: string
                      description: The name of the service.
                      example: frontend
                    environment:
                      type: string
                      description: The environment of the service.
                      example: production
                  required:
                    - name
                etag:
                  type: string
                  description: etag is sent by the APM agent to indicate the etag of the last successfully applied configuration. If the etag matches an existing configuration its `applied_by_agent` property will be set to `true`. Every time a configuration is edited `applied_by_agent` is reset to `false`.
                  example: 1e58c178efeebae15c25c539da740d21dee422fc
              required:
                - service
                - etag
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _index:
                    type: string
                    example: .apm-agent-configuration
                  _id:
                    type: string
                    example: CIaqXXABmQCdPphWj8EJ
                  _score:
                    type: number
                    example: 2
                  _source:
                    type: object
                    properties:
                      agent_name:
                        type: string
                        example: nodejs
                      service:
                        type: object
                        properties:
                          name:
                            type: string
                            example: frontend
                      settings:
                        type: object
                        example:
                          transaction_sample_rate: '1'
                      '@timestamp':
                        type: number
                        example: 1582031336265
                      applied_by_agent:
                        type: boolean
                        example: false
                      etag:
                        type: string
                        example: 5080ed25785b7b19f32713681e79f46996801a5b
components: {}
